### ISSUE TITLE
Does tgstore have persistence data forever until telegram delete them? and When?

### ISSUE THREAD

**Issue by abserari** [golang-design/tgstore#2]

**Comment by aofei** [comment]
AFAIK, they have no plans to delete any data. So for this project, theoretically all data is permanently stored.

https://twitter.com/telegram/status/1222955852681875457

**Comment by abserari** [comment]
I see, I need to create a private group to save messages, not only chat with my user account. 

And Notice: If your telegram account does not active six mouths. Data would be cleared.

**Comment by aofei** [comment]
Also check [this](https://twitter.com/telegram/status/1344282092461412353).
