### ISSUE TITLE
Question on file stored time

### ISSUE THREAD

**Issue by LoSunny** [golang-design/tgstore#3]
According to the telegram document
```
Bots have limited cloud storage — older messages may be removed by the server shortly after they have been processed.
```
https://core.telegram.org/bots
So how can I ensure my data is stored in the cloud forever?

**Comment by aofei** [comment]
I think you got it wrong. The "old messages" in that sentence doesn't refer to the messages your bot sent to the Telegram's servers, but the messages (more precisely, [updates](https://core.telegram.org/bots/api#update)) that they tries to send to your bot.

What I know so far is that they'll not delete any files you upload (see https://github.com/golang-design/tgstore/issues/2#issuecomment-751722486). I uploaded a considerable amount of files for years and they're still there.

However, there is no real "forever" in the internet. So, never store your important data in only one place, make sure they're backed up in different other places.

**Comment by LoSunny** [comment]
Oh, I get it now, thanks for the clarification 👍
